### ISSUE TITLE
Determine Profiles functionality

### ISSUE THREAD

**Issue by vlandham** [vlandham/salonpals#1]
Our original idea was to start with basic profiles as a place for users to highlight their skills. We are not putting social network features into salonpals for now.

With this limited concept of profiles, we have to figure out what we actually want users to be able to do with profiles - or perhaps exclude them completely from the initial release. 

With no 'friend'-like associations, profile searching and display as seen in linked-in doesn't work. There is no reason to search by name / company - because there is nothing to do with the search results (i.e. you can't 'friend' anyone you find). So employee's on the site have no need to search / view any profiles but their own. 

If we want this to replace the resume, then here would be my suggestions for profile features:
- user gets an empty profile when they create an account
- users can fill in profile at any time
- job poster can see all the profiles for the people that have applied for a job post
- profile contains:
  - 'about me' section
  - skills section
  - previous experience section

And thats about it. So their would be no searching of profiles, and a profile would only be used as a resume when a user applies for a job.

What are your thoughts on this?

**Comment by k10dev** [comment]
I agree with your assessment of the profile feature. Without the social networking aspect, it would not work well. We definitely should exclude it from the initial release.

Your suggestions for a basic profile features would work for me.

In my opinion, the crucial features for the initial release are job search and job post. As long as we able to get these 2 features work well, the rest can be pushed back for later.

**Comment by vlandham** [comment]
Ok - so should we try to get basic profiles working - or just exclude it completely?

**Comment by k10dev** [comment]
I think we should just exclude it completely for the initial release to focus on the main features.

**Comment by vlandham** [comment]
Ok, I'll open a new ticket with this basic profile for the next release
