### ISSUE TITLE
Need 'Required Skills' for job postings

### ISSUE THREAD

**Issue by vlandham** [vlandham/salonpals#2]
As we discussed a while back, a main feature of job postings will be a section called something like 'Required Skills' - which will be a point and click way to add skills that the applicant should have. 

I'm still working on a UI for this feature. 

Right now the backend is set up to have 'Skills' and 'SkillCategories' - with a many to many relationship between them. And a job post can have many 'Skills'

The idea is that a skill can be 'tagged' by a skillcategory - and then this will be used as a two-tier navigation structure for when the user is choosing required skills.

We need to some how get a collection of skills and skill categories to populate our database with.
Each skill and skill category should be translated in both English and Vietnamese.

Is this something your wife could work on?

**Comment by k10dev** [comment]
I will do research or talk to some people I know to collect the skills and skill categories for this feature.
