### ISSUE TITLE
Mobile version of all pages

### ISSUE THREAD

**Issue by vlandham** [vlandham/salonpals#3]
The mobile side of the site needs to be finished with all sections function.
We might consider limiting some features on the mobile side - such as creating a new job post.

**Comment by k10dev** [comment]
I think it's OK to limit some features on the mobile side for now. A lot of people still like to use the normal site even on the mobile devices.

**Comment by vlandham** [comment]
Ok. 
Features for mobile side in initial beta release:
- View job postings | salons for sale | booths for Rent
- Apply for job posting
- Search for job postings
- Manage job postings
- Modify user info

Not included
- Creation of new job post
- Any of the Admin section of the site
